spring:
  application:
    name: legal-sales-sidekick
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/legal_sales
    username: akhil
    password: "@Khil401"
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
google:
  client_id: ''
  client_secret: ''
