spring:
  application:
    name: legal-sales-sidekick
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/legal_sales
    username: postgres
    password: "akhil401"
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
google:
  clientId: '163163550532-fav9ts599hreo8kgkj4gtv23jbqv2q43.apps.googleusercontent.com'
